version: '3'
services:
    service01:
        build: ./service-01
        volumes:
            - /service-01/node_modules
        ports:
            - "8001:8001"
        networks:
                backend:
    service02:
        build: ./service-02
        volumes:
          - /service-02/node_modules
        networks:
            backend:
networks:
    backend:

