version: '3'
services:
    rabbitmqserver:
        image: rabbitmq:latest
        container_name: 'rabbitmqserver'
        ports:
            - "5672"
            - "15672"
        networks:
            - rabbitmq_go_net
    orig:
        build: ./orig
        restart: on-failure
        ports:
            - "5672"
        networks:
            -   rabbitmq_go_net
        command: ["./wait-for-it.sh", "rabbitmqserver:15672", "--", "node", "ORIG.js"]

    imed:
        build: ./imed
        restart: on-failure
        ports:
            - "5672"
        networks:
            -   rabbitmq_go_net
        command: ["./wait-for-it.sh", "rabbitmqserver:15672", "--", "node", "IMED.js"]


    obse:
        build: ./obse
        restart: on-failure
        ports:
            - "5672"
        volumes:
            - ./logs:/logs 
        networks:
            -   rabbitmq_go_net
        command: ["./wait-for-it.sh", "rabbitmqserver:15672", "--", "node", "OBSE.js"]


    httpserver:
        build: ./httpserve
        ports:
            - "8080:3001"
        volumes:
            - ./logs:/logs

networks:
    rabbitmq_go_net:
        driver: bridge