version: '3'
services:
    rabbitmq:
        image: rabbitmq:latest
        container_name: 'rabbitmq'
        ports:
            - "5672"
            - "15672"
        networks:
            - rabbitmq_go_net
    orig:
        build: ./orig
        ports:
            - "5672"
        networks:
            -   rabbitmq_go_net
        depends_on:
            rabbitmq:
                condition: service_completed_successfully

    imed:
        build: ./imed
        ports:
            - "5672"
        networks:
            -   rabbitmq_go_net
        depends_on:
            rabbitmq:
                condition: service_completed_successfully

    obse:
        build: ./obse
        ports:
            - "5672"
        volumes:
            - ./logs:/logs 
        networks:
            -   rabbitmq_go_net
        depends_on:
            rabbitmq:
                condition: service_completed_successfully  

    httpserver:
        build: ./httpserve
        ports:
            - "8001:3001"
        networks:
            -   backend
        volumes:
            - ./logs:/logs
networks:
    rabbitmq_go_net:
        driver: bridge