---
    - hosts: all
      #connection: local # When running locally
      vars:
        package_names:
          - vim
          - git
      tasks:
        - name: "Check if listed package is installed or not on Debian Linux family"
          command: dpkg-query -l "{{ item }}"
          loop: "{{ package_names }}"
          register: package_check
          when: ansible_facts['os_family'] == "Debian"
    
        - name: "Check if listed package is installed or not on Red Hat Linux family"
          command: rpm -q "{{ item }}"
          loop: "{{ package_names }}"
          register: package_check
          when: ansible_facts['os_family'] == "RedHat"
        - name: "Print execution results"
          debug:
            msg: "Package is installedgf"
          when: package_check is succeeded

        - name: Get uptime first
          shell: uptime
          register: hello
          - debug: msg="{{ hello.stdout }}"
          - debug: msg="{{ hello.stderr }}"